#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Buki\Commands\CreateControllerCommand());
$application->add(new \Buki\Commands\CreateMiddlewareCommand());

$application->run();

